# -*- coding: utf-8 -*-
"""
Created on Thu Jul 22 12:14:07 2021

@author: siumichael.tang
"""

import os 
import re
import pandas as pd
import numpy as np
import nibabel as nib 

#import myfunction
from myfunction import get_path, sort_elect

#---------------------------------------------------------------------------
#---------------------------------------------------------------------------
# BEGIN USER INPUT

# enter subject number (str)
subnum = '14';

# enter path to directory where all input files are located
directname = '/work/levan_lab/mtang/fmri_project/' + 'sub' + subnum
#directname = 'C:\\Users\\siumichael.tang\\Downloads\\fmri_project\\' + 'sub' + subnum

# format filenames of processed fmri images, explicit mask, electrode,
# motion parameters
filename_swraimg = '^swra.*\.nii$'   # processed func. images
filename_expmask = 'wEPI_bet_mask\.nii'   # explicit mask
filename_elect = subnum + '_.*Koordinaten.*\.xlsx'  # file containing mni coord. of all electrode pairs
filename_spikes = 'subject' + subnum + '_rates\.txt'   # file of spike rates
filename_motion = 'rp_.*\.txt'   # motion parameters generated by SPM in the realignment step

# enter path where ouput struct. is stored at
#fname_op = [directname, filesep, 'matrices' filesep 'reho_alff_spikes']   # direct. of output matrix
#eafilename_op = 'reho_alff_spikes.mat'   # filename of output file

# enter if output should be written to path (1 = yes, 0 = no)
op_results = 0

# END USER INPUT
#---------------------------------------------------------------------------
#---------------------------------------------------------------------------
        
# use get_path function to obtain full path of input files
swra_file_path = get_path(directname, filename_swraimg)   # swra func. images
expmask_file_path = get_path(directname, filename_expmask)   # normalized mask images
elect_file_path = get_path(directname, filename_elect)   # file containing info. about electrodes coordinates
spikes_file_path = get_path(directname, filename_spikes)   # spike rates
motion_file_path = get_path(directname, filename_motion)   # motion parameters

# load processed images
run_ind = 0;

# create instance of processed image
swra_inst = nib.load(swra_file_path[run_ind])

# use get_fdata() method to obtain the actual image
# and use attribute, header, to obtain metadata (dict)
swra_img = swra_inst.get_fdata()   # actual image data
swra_header = swra_inst.header   # metadata about the image

# create instance of explicit mask, then get exp. mask image data
expmask = nib.load(expmask_file_path[0]).get_fdata()

# load electrode coordiantes from .xlsx file into dataframe, 
# selected only first 4 columns
elect_df = pd.read_excel(elect_file_path[0], usecols = list(range(5)))

# load spike rates from .txt file into dataframe, specify ' ' delimiter
spikes_df = pd.read_csv(spikes_file_path[0], sep = ' ')

# load motion parameters from .txt file into numpy array
motion_para = np.loadtxt(motion_file_path[run_ind])

#---------------------------------------------------------------------------
# Part (I): remove motion artifacts from processed image (entire brain)

# apply element-wise multiplciation btw. explicit mask and swra images
exp_swra_img = np.zeros(swra_img.shape)   # initialize array
for t in range(swra_img.shape[-1]):   # for swra img at every instant in time
    exp_swra_img[:, :, :, t] = expmask * swra_img[:, :, :, t]   
                
# call filter_motion.m to remove motion artifacts from image
#motion_filtered_img = filter_motion(motion_file_path, exp_swra_img);

# END Part (I): remove motion artifacts from processed images
#---------------------------------------------------------------------------



#---------------------------------------------------------------------------

# Part (IV): sort electrodes by their types

# use sort_elect to sort electrode array by their types
ele_sorted = sort_elect(elect_df);

# END PART (IV): sorte electrodes by their types
#---------------------------------------------------------------------------

# Part (V): find midpoint of each pair of electrode contacts in both mni
# and image space


#---------------------------------------------------------------------------
# Part (I): find midpoint of each pair of electrode contacts

# initialize list for storing midpoint of every channel (electrode pair)
# in this nested list, every entry contains a list with format given below:
# 1st entry = name tag of channel
# 2nd entry = list of midpt corrdinates [x, y, z]
midpt = []

# scan across every row within every entry in sorted ele. list, 
# then assemble name tag of channel, 
# and compute midpoint of x-, y-, and z-coordinates
for i in range(len(ele_sorted)):   # every entry in sorted ele. list
    cur_list = []   # initialize list for storing info. of curr. ele. type
    # within curr. entry in nested list, scan across every sub-entry, 
    # format name tag for channel and compute midpoint
    for j in range(len(ele_sorted[i]) - 1):
        pair_name = ele_sorted[i][j][0] + '-' + ele_sorted[i][j+1][0]
        mx = 0.5*(ele_sorted[i][j][1] + ele_sorted[i][j+1][1]) 
        my= 0.5*(ele_sorted[i][j][2] + ele_sorted[i][j+1][2]) 
        mz= 0.5*(ele_sorted[i][j][3] + ele_sorted[i][j+1][3])
        
        # append info. of every channel to curr. list (curr. ele. type)
        cur_list.append([pair_name, [mx, my, mz]])      
        
    # after looping through all elements in current entry (all channels in 
    # current type, append curr. list to nested list, midpt)
    midpt.append(cur_list)
        
# END Part (I): find midpoint of each pair of electrode contacts                        
#---------------------------------------------------------------------------
# Part (II): convert coordinates from mni space to image space
                                  
# Part (II): convert coordinates from mni space to image space
#---------------------------------------------------------------------------






# MNI TO IJK
input_list = [-35, 5, 10]
mnicoord = [-35, 5, 10]

srow_x = swra_header['srow_x']
srow_y = swra_header['srow_y']
srow_z = swra_header['srow_z']

srowmat = np.array([srow_x[:3], srow_y[:3], srow_z[:3]]) 

matb3 = mnicoord - [srow_x[-1], srow_y[-1], srow_z[-1]]  
        
# END Part (V): find midpoint of each pair of electrode contacts in both mni
# and image space
#---------------------------------------------------------------------------

